/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'franzi' at '14.10.14 15:33' with Gradle 2.1
 *
 * @author franzi, @date 14.10.14 15:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
